.gitignore
ar-lib is an autotools helper script.
tags, TAGS, cscope.* and ncscope.* are files generated by ctags and cscope,
source code analysers and navigation tools.
=> .gitignore: add missing files that should be ignored

xlat/gen.sh
* xlat/gen.sh (gen_header): Replace 3>- with 3>&-.
=> xlat: fix file descriptor closing typo

src/sync_file_range.c, src/sync_file_range2.c
With the following commands,
```
$ ./bootstrap
$ _pkg_arch=aarch64
$ export PATH="/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
$ CC=$_pkg_arch-linux-android21-clang \
./configure --prefix=/opt/android-libs/${_pkg_arch/_/-} \
--host=$_pkg_arch-linux-android \
--without-libunwind \
--enable-mpers=no \
--disable-gcc-Werror
$ make
```
Building fails with:
```
In file included from sync_file_range.c:12:
./xlat/sync_file_range_flags.h:7:16: error: use of undeclared identifier 'SYNC_FILE_RANGE_WAIT_BEFORE'
static_assert((SYNC_FILE_RANGE_WAIT_BEFORE) == (1), "SYNC_FILE_RANGE_WAIT_BEFORE != 1");
^
./xlat/sync_file_range_flags.h:10:16: error: use of undeclared identifier 'SYNC_FILE_RANGE_WRITE'
static_assert((SYNC_FILE_RANGE_WRITE) == (2), "SYNC_FILE_RANGE_WRITE != 2");
^ …
```
=> Fix building for older Android

NEWS, bundled/Makefile.am, bundled/linux/include/uapi/linux/futex.h, src/Makefile.am, src/futex_waitv.c, src/linux/generic/syscallent-common.h, src/xlat/futex_waiter_flags.in, tests/.gitignore, tests/futex_waitv.c, tests/gen_tests.in, tests/pure_executables.list
Hi,
This is an initial implementation of the new `futex_waitv()` syscall decoding that will be merged at Linux 5.16.
Documentation from the [commit message](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=bf69bad38cf63d980e8a603f8d1bd1f85b5ed3d9):
Add support to wait on multiple futexes. This is the interface implemented by this syscall:
```
futex_waitv(struct futex_waitv *waiters, unsigned int nr_futexes,
unsigned int flags, struct timespec *timeout, clockid_t clockid)
struct futex_waitv {
__u64 val;
__u64 uaddr;
__u32 flags;
__u32 __reserved;
};
```
Given an array of `struct futex_waitv`, wait on each `uaddr`. The thread wakes if a `futex_wake()` is performed at any `uaddr`. The syscall returns immediately if any waiter has `*uaddr != val`. `*timeout` is an …
=> Implement futex_waitv syscall decoding

src/linux/loongarch64/arch_prstatus_regset.c, src/linux/loongarch64/get_syscall_args.c, tests/ptrace.c
(continuing from #205)
With the LoongArch `struct user_pt_regs` definition amended to [expose the `orig_a0` field](https://github.com/loongson/linux/blob/3643df5f058aacf69ac4121f6882500e843b7a34/arch/loongarch/include/uapi/asm/ptrace.h#L35), I've integrated the changes into [my kernel branch](https://github.com/xen0n/linux/commits/loongarch-playground-v11-draft) and passed the tests with this PR:
```
============================================================================
Testsuite summary for strace 5.16.0.37.1e18
============================================================================
============================================================================
```
`uname -a`: `Linux lily 5.17.0-rc1-12006-g03f57a04a4f1 #3 SMP PREEMPT Thu Nov 25 11:42:54 PM CST 2021 loongarch64 …
=> loongarch64: make use of the newly exposed orig_a0 field for ptrace

NEWS, configure.ac, src/printsiginfo.c, tests/.gitignore, tests/Makefile.am, tests/gen_tests.in, tests/ptrace.c, tests/segv_accerr.c, tests/segv_pkuerr.c
This adds decoding of `si_pkey` field  which is set on `SIGSEGV` in case
of memory access violation on some modern CPUs (these have `pku` flag in `/proc/cpuinfo`).
Here's few sample outputs:
```
pkey_alloc(0, 0)                        = 3
pkey_mprotect(0x7f3f20662000, 4096, PROT_READ|PROT_WRITE, 3) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_PKUERR, si_addr=0x7f3f20662000, si_pkey=3} ---
```
or another case:
```
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f137374b000
mprotect(0x7f137374b000, 4096, PROT_EXEC) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_PKUERR, si_addr=0x7f137374b000, si_pkey=1} ---
```
=> printsiginfo: decode si_pkey field

.github/workflows/differential-shellcheck.yml
Differential ShellCheck requires permission `security-events: write` to upload the SARIF file to GitHub successfully.
This permission might be optional for some repositories since they allow all permissions for all workflows in settings. But I wouldn't advise this setting since the best security practice is to allow only a minimal set of required permissions.
Failed to upload SARIF - [logs](https://github.com/strace/strace/actions/runs/3980140518/jobs/6823022346#step:4:31)
=> Add missing permission `security-events` for Differential ShellCheck GA

tests/Makefile.am
getpid and getppid are already listed in $(PURE_EXECUTABLES). Remove the duplicate entries.
=> tests: remove getpid and getppid from check_PROGRAMS

src/linux/mips/raw_syscall.h
Some of the tests use a custom function (raw_syscall_0) for syscall invocation.
The implementation for mips was flawed: it unconditionally clobbered "hi" and "lo", which is not valid for MIPS R6, because these targets lack those registers w/o DSP extension.
GCC 10+ refuses to compile such constructs: [1], [2].
Fix the syscall invocation implementation for mips.
[1] https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=0a59215131c02dee4c8829f93d1ee678647614da
[2] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91233
* src/linux/mips/raw_syscall.h: Add SYSCALL_CLOBBERLIST.
(raw_syscall_0): Use it.
=> mips: fix raw_syscall_0

configure.ac, tests/Makefile.am
--enable-install-test-binaries=yes installs binaries from the test suite to $libexec/strace.
This flag does not install everything necessary to run the tests (no harness), but at least installs the binaries.
This can be useful when debugging various targets
and how strace behaves on them.
This can also be extended later with a standalone test harness that would not depend on the build directory to be present on the target.
* configure.ac: Add --enable-install-test-binaries.
* tests/Makefile.am: Add testslibexecdir, testslibexec_PROGRAMS.
=> Add a configure flag for installing tests

debian/control
This commit incorporates a change from Debian's packaging: "a another" is replaced with "another".
Note that there is another change in Debian packaging which I'm skipping on purpose since it is not correct as far as I know: "tracer, i.e." becoming "tracer: i.e.".
=> debian/control: fix wording in description

src/msghdr.c, tests/gen_tests.in, tests/netlink_generic.c
Some clients, e.g. ovs-dpctl, use sendmsg with a connected socket so the address family cannot be identified by msg_name. Look up the fd proto when msg_name is NULL.
=> Identify netlink by proto when msghdr.msg_name is not set

NEWS, src/strace.c
strace -r decides whether the previous timespec has been initialized by
checking if `tv_sec == 0`. However, in the second after booting,
`CLOCK_MONOTONIC` will legitimately have a `tv_sec` of 0. This causes every
displayed timestamp to display as `0.000000` during the second after boot.
Check `tv_nsec` as well before assuming the previous timespec is uninitialized.
-----
Originally discovered in a freshly booted virtual system, amusingly while
trying to use strace to debug a similar issue in ping:
https://github.com/iputils/iputils/pull/499
=> Fix strace -r during the second after booting

NEWS, src/strace.c, tests/.gitignore, tests/Makefile.am, tests/detach-vfork.c, tests/detach-vfork.test
strace is likely to block at terminate if tracee is forking. on linux, calling vfork will cause the calling thread to 'D' state until the child process calls execve. But the child process is attached by default and will block when the fork system call returns. therefore strace must detach child process first, otherwise it will enter infinit waiting for the 'D' state thread.
the golang test code:
```
package main
import (
"os/exec"
"syscall"
)
var rc = make(chan int, 10)
func run() {
cmd := exec.Command("sh", []string{"-c", "uname -a"}...)
attr := syscall.SysProcAttr{ Setpgid: true }
cmd.SysProcAttr = &attr
cmd.Run()
<-rc
return
}
func main() {
for {
rc <- 1
go run()
}
}
```
use `go run test.go` to start the test code. and `strace -fp <pid>` attach to the test code. 'Ctrl+c' very likely …
=> strace -f: fix potential deadlock during cleanup

.github/dependabot.yml, .github/workflows/differential-shellcheck.yml
- update `actions/upload-artifact` to eliminate the error message: `Node.js 16 actions are deprecated. ...`
- enable Dependabot to keep GitHub Actions up to date
=> Enable Dependabot and update GitHub Actions to latest versions

NEWS, doc/strace.1.in, src/defs.h, src/strace.c, src/unwind-libdw.c, src/unwind-libunwind.c, src/unwind.c, src/unwind.h, tests/Makefile.am, tests/options-syntax.test, tests/strace-k-with-depth-limit.expected, tests/strace-k-with-depth-limit.test, tests/strace-k.test
This change adds a `--stacktrace-frames-limit` command line options, which controls the limit of number of frames we print during backtracing (`-k`) a syscall
* NEWS: Mention this
* doc/strace.1.in: Document this
* src/defs.h: New constant DEFAULT_STACKTRACE_FRAMES_LIMIT.
(unwind_init): Add an int parameter
* src/strace.c (stack_trace_enabled): 
[ENABLE_STACKTRACE]: Add --stacktrace-frames-limit=N option.
[ENABLE_STACKTRACE] (init): Handle --stacktrace-frames-limit option.
(init): Pass the limit to unwind_init() if --stacktrace-frames-limit is given.
* src/unwind.h (struct unwind_unwinder_t::init): Add an int parameter.
* src/unwind.c (unwind_init): Pass the limit parameter to the unwinder initializer.
* src/unwind-libdw.c (tcb_walk): Use the newly added parameter at frame_user_data …
=> add --stacktrace-frames-limit support for unwinding

src/kernel_v4l2_types.h, src/v4l2.c, tests/ioctl_v4l2-success.c, tests/ioctl_v4l2.c
On 32-bit kernels there are older variants of VIDIOC_QBUF, VIDIOC_DQBUF, and VIDIOC_QUERYBUF ioctls, which have _TIME32 suffix. These are for old timeval_t with 32-bit timestamps. Some 32-bit applications still use these.
Implement printing these variants alongside regular 64-bit time ones.
=> v4l2: add VIDIOC_QBUF_TIME32 and friends

src/strace.c, tests/options-syntax.test, tests/syntax.sh
The original code accepts only one delimiter between PIDs. This change relaxes the condition.
* src/strace.c (process_opt_p_list): Skip the consecutive delimiters.
* tests/syntax.sh (check_zero): New helper function.
* tests/options-syntax.test: Add code testing this change.
=> Make -p options accept multiple delimiters between PIDs

src/defs.h, src/ioctl.c, src/util.c, tests/.gitignore, tests/dev-pty-yy.c, tests/gen_tests.in, tests/pure_executables.list
An example output:
read(32</dev/ptmx<char 5:2->/dev/pts/7>>, "\0\"\\0", 4) = 4
* src/defs.h (struct finfo::tty_index): New member. (get_finfo_for_dev): Add two parameters.
* src/ioctl.c (SYS_FUNC(ioctl)): Pass pid and fd to get_finfo_for_dev().
* src/utils.c (scan_fdinfo, scan_fdinfo_fn): Declare earlier. (is_ptmx): New macro.
(get_pts): New function.
(get_finfo_for_dev): Read the tty-index field in /proc/$pid/fdinfo/$fd and store the value to struct finfo::tty_index.
(printenv): Pass pid and fd to get_finfo_for_dev(). Print the slave device for the fd opening /dev/ptmx as the counter endpoint.
* tests/dev-pty-yy.c: New test case.
* tests/gen_tests.in: Add dev-pty-yy.
* tests/pure_executables.list: Add dev-pty-yy.
=> Show the slave device for the fd opening /dev/ptmx when -yy is given

NEWS, doc/strace.1.in, src/strace.c, tests/options-syntax.test
When building strace statically linked using the "--username" argument will lead to strange errors. The reason is that the calls to getpwnam() and initgroups() will fail because glibc will still try to dlopen() the libnss modules which then fails in unexpected ways.
The `--username` argument is only needed for uid:gid and supplementary groups setup. So this commit provides a way to pass uid:gid via the commandline and it will not init supplementary groups (but it could be extended for this).
This does allow to use a statically linked strace.
=> strace: add support for -u UID:GID that bypasses lookup

NEWS, doc/strace.1.in, src/strace.c, tests/.gitignore, tests/gen_tests.in, tests/pure_executables.list, tests/strace--always-show-pid.c
By default, PID prefixes are only printed for children forked from the process started by strace. With this option, prefixes are printed for the process started by strace as well.
Close #278
=> Add option --always-show-pid

src/print_utils.h
`gcc-15` added a new warning in https://gcc.gnu.org/PR115185:
print_utils.h:16:35: error: initializer-string for array of 'char' is too long [-Werror=unterminated-string-initialization]
16 | static const char hex_chars[16] = "0123456789abcdef";
|                                   ^~~~~~~~~~~~~~~~~~
`strace` does not need to store '\0'. We could either initialize the arrays with individual bytes or allocate extra byte for null.
This change initializes the array bytewise.
=> print_utils.h: initialize `hex_chars` as an array, not via string

src/defs.h
* src/defs.h (translate_pid): s/dest_id/from_id/.
=> defs.h: fix a typo in a name of parameter

NEWS, src/ioctl.c, tests/.gitignore, tests/gen_tests.in, tests/ioctl-v.c, tests/pure_executables.list
This change adds the ability to print the payload of ioctls that aren't explicitly supported by strace, provided that the ioctl number follows modern Linux conventions.
Example output: (cherry-picked test output from tests/ioctl.c)
```
ioctl(-1, MMTIMER_GETRES, "\x00\x00\x00\x00\x00\x00\x00\x00") = -1 EBADF (Bad file descriptor)
ioctl(-1, VIDIOC_ENUMINPUT, NULL) = -1 EBADF (Bad file descriptor)
ioctl(-1, HIDIOCGRDESCSIZE or HIDIOCGVERSION, "\x00\x00\x00\x00") = -1 EBADF (Bad file descriptor)
ioctl(-1, _IOC(_IOC_READ, 0xde, 0xad, 0x8), "\xfe\xed\xfa\xce\xde\xad\xbe\xef") = -1 EBADF (Bad file descriptor)
ioctl(-1, _IOC(_IOC_WRITE, 0xde, 0xad, 0x8), "\xfe\xed\xfa\xce\xde\xad\xbe\xef") = -1 EBADF (Bad file descriptor)
ioctl(-1, _IOC(_IOC_READ|_IOC_WRITE, 0xde, 0xad, 0x8), …
```
=> ioctl: Hex-dump arg buffer for unknown ioctls

src/sched_attr.h
glibc 2.41+ has added [1] definitions for sched_setattr and sched_getattr functions and struct sched_attr. Therefore, it needs to be checked for here as well before defining sched_attr
Fixes builds with glibc/trunk
In file included from ../../strace-6.11/src/sched.c:14: ../../strace-6.11/src/sched_attr.h:16:8: error: redefinition of 'sched_attr'
16 | struct sched_attr {
|        ^
/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux/strace/6.11/recipe-sysroot/usr/include/linux/sched/types.h:98:8: note: previous definition is here
98 | struct sched_attr {
|        ^
[1] https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=21571ca0d70302909cf72707b2a7736cf12190a0;hp=298bc488fdc047da37482f4003023cb9adef78f8
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> sched_attr: Define conditionally on SCHED_ATTR_SIZE_VER1

src/sched_attr.h, tests/sched_xetattr.c
The recent addition of struct sched_attr to glibc deliberately used Linux types to simplify porting from `<linux/sched.h>` to `<sched.h>`. Switch the bundled definition here to `__u32` and `__u64` as well.
=> sched_attr: Use Linux types in struct sched_attr

tests/init.sh, tests/legacy_syscall_info.test
Kernel commit [61119394631f219e](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=61119394631f219e23ce98bcc3eb993a64a8ea64) ("riscv: entry: always initialize regs->a0 to -ENOSYS") made the legacy API unusable for us, which means that the test always fails when using a recent kernel.
Closes: https://github.com/strace/strace/issues/315
=> tests: Skip legacy_syscall_info on riscv64 with kernel 6.11+

src/v4l2.c, tests/ioctl_v4l2-success.c, tests/ioctl_v4l2.c
```
Decode the `VIDIOC_EXPBUF` v4l2 ioctl as follows:
ioctl(17</dev/video10>,
VIDIOC_EXPBUF,
{type=V4L2_BUF_TYPE_VIDEO_CAPTURE, index=2, plane=0, flags=O_RDWR|O_CLOEXEC}
=> {fd=25</dmabuf:>}) = 0 <0.000091>
Every current field is supported, the `fd` field is decoded on return.
* src/v4l2.c: Decode `VIDIOC_EXPBUF`.
* tests/ioctl_v4l2.c: Remove `VIDIOC_EXPBUF` from list of unsupported ioctls, and add some `VIDIOC_EXPBUF` tests.
```
PS: I couldn't subscribe to the mailing list, so here it is.
=> v4l2: decode `VIDIOC_EXPBUF`
